/* 24/24 EVERYWHERE — liste des langues. © 2026 Sébastien Chevrier. Tous droits réservés.
   COPIE EXACTE de la liste LANGUAGES de 24/24 TALK (index.html), pour que EVERYWHERE propose les mêmes langues,
   avec les mêmes codes de traduction et de voix. Si la liste de TALK change, recopier ici (voir README). */
window.EW_LANGS = [
  // --- Europe ---
  { code: "fr", name: "Français", flag: "🇫🇷", speech: "fr-FR", region: "Europe" },
  { code: "en", name: "Anglais", flag: "🇬🇧", speech: "en-US", region: "Europe" },
  { code: "es", name: "Espagnol", flag: "🇪🇸", speech: "es-ES", region: "Europe" },
  { code: "de", name: "Allemand", flag: "🇩🇪", speech: "de-DE", region: "Europe" },
  { code: "it", name: "Italien", flag: "🇮🇹", speech: "it-IT", region: "Europe" },
  { code: "pt", name: "Portugais", flag: "🇵🇹", speech: "pt-PT", region: "Europe" },
  { code: "pt-BR", name: "Portugais (Brésil)", flag: "🇧🇷", speech: "pt-BR", region: "Amériques" },
  { code: "nl", name: "Néerlandais", flag: "🇳🇱", speech: "nl-NL", region: "Europe" },
  { code: "pl", name: "Polonais", flag: "🇵🇱", speech: "pl-PL", region: "Europe" },
  { code: "ro", name: "Roumain", flag: "🇷🇴", speech: "ro-RO", region: "Europe" },
  { code: "el", name: "Grec", flag: "🇬🇷", speech: "el-GR", region: "Europe" },
  { code: "cs", name: "Tchèque", flag: "🇨🇿", speech: "cs-CZ", region: "Europe" },
  { code: "sv", name: "Suédois", flag: "🇸🇪", speech: "sv-SE", region: "Europe" },
  { code: "da", name: "Danois", flag: "🇩🇰", speech: "da-DK", region: "Europe" },
  { code: "nb", name: "Norvégien", flag: "🇳🇴", speech: "nb-NO", region: "Europe" },
  { code: "fi", name: "Finnois", flag: "🇫🇮", speech: "fi-FI", region: "Europe" },
  { code: "hu", name: "Hongrois", flag: "🇭🇺", speech: "hu-HU", region: "Europe" },
  { code: "bg", name: "Bulgare", flag: "🇧🇬", speech: "bg-BG", region: "Europe" },
  { code: "hr", name: "Croate", flag: "🇭🇷", speech: "hr-HR", region: "Europe" },
  { code: "sk", name: "Slovaque", flag: "🇸🇰", speech: "sk-SK", region: "Europe" },
  { code: "sl", name: "Slovène", flag: "🇸🇮", speech: "sl-SI", region: "Europe" },
  { code: "lt", name: "Lituanien", flag: "🇱🇹", speech: "lt-LT", region: "Europe" },
  { code: "lv", name: "Letton", flag: "🇱🇻", speech: "lv-LV", region: "Europe" },
  { code: "et", name: "Estonien", flag: "🇪🇪", speech: "et-EE", region: "Europe" },
  { code: "is", name: "Islandais", flag: "🇮🇸", speech: "is-IS", region: "Europe" },
  { code: "ga", name: "Irlandais", flag: "🇮🇪", speech: "ga-IE", region: "Europe" },
  { code: "mt", name: "Maltais", flag: "🇲🇹", speech: "mt-MT", region: "Europe" },
  { code: "sq", name: "Albanais", flag: "🇦🇱", speech: "sq-AL", region: "Europe" },
  { code: "mk", name: "Macédonien", flag: "🇲🇰", speech: "mk-MK", region: "Europe" },
  { code: "sr", name: "Serbe", flag: "🇷🇸", speech: "sr-RS", region: "Europe" },
  { code: "bs", name: "Bosniaque", flag: "🇧🇦", speech: "bs-BA", region: "Europe" },
  { code: "uk", name: "Ukrainien", flag: "🇺🇦", speech: "uk-UA", region: "Europe" },
  { code: "be", name: "Biélorusse", flag: "🇧🇾", speech: "be-BY", region: "Europe" },
  { code: "ru", name: "Russe", flag: "🇷🇺", speech: "ru-RU", region: "Europe" },
  { code: "ca", name: "Catalan", flag: "🇪🇸", speech: "ca-ES", region: "Europe" },
  { code: "eu", name: "Basque", flag: "🇪🇸", speech: "eu-ES", region: "Europe" },
  { code: "gl", name: "Galicien", flag: "🇪🇸", speech: "gl-ES", region: "Europe" },
  { code: "cy", name: "Gallois", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", speech: "cy-GB", region: "Europe" },
  { code: "lb", name: "Luxembourgeois", flag: "🇱🇺", speech: "lb-LU", region: "Europe" },

  // --- Moyen-Orient ---
  { code: "ar", name: "Arabe", flag: "🇸🇦", speech: "ar-SA", region: "Moyen-Orient" },
  { code: "he", name: "Hébreu", flag: "🇮🇱", speech: "he-IL", region: "Moyen-Orient" },
  { code: "fa", name: "Persan (Farsi)", flag: "🇮🇷", speech: "fa-IR", region: "Moyen-Orient" },
  { code: "tr", name: "Turc", flag: "🇹🇷", speech: "tr-TR", region: "Moyen-Orient" },
  { code: "ku", name: "Kurde", flag: "🌐", speech: "ku", region: "Moyen-Orient" },
  { code: "ps", name: "Pachto", flag: "🇦🇫", speech: "ps-AF", region: "Moyen-Orient" },
  { code: "az", name: "Azéri", flag: "🇦🇿", speech: "az-AZ", region: "Moyen-Orient" },
  { code: "hy", name: "Arménien", flag: "🇦🇲", speech: "hy-AM", region: "Moyen-Orient" },
  { code: "ka", name: "Géorgien", flag: "🇬🇪", speech: "ka-GE", region: "Moyen-Orient" },

  // --- Afrique ---
  { code: "sw", name: "Swahili", flag: "🇰🇪", speech: "sw-KE", region: "Afrique" },
  { code: "am", name: "Amharique", flag: "🇪🇹", speech: "am-ET", region: "Afrique" },
  { code: "ha", name: "Haoussa", flag: "🇳🇬", speech: "ha", region: "Afrique" },
  { code: "yo", name: "Yoruba", flag: "🇳🇬", speech: "yo-NG", region: "Afrique" },
  { code: "ig", name: "Igbo", flag: "🇳🇬", speech: "ig-NG", region: "Afrique" },
  { code: "zu", name: "Zoulou", flag: "🇿🇦", speech: "zu-ZA", region: "Afrique" },
  { code: "xh", name: "Xhosa", flag: "🇿🇦", speech: "xh-ZA", region: "Afrique" },
  { code: "af", name: "Afrikaans", flag: "🇿🇦", speech: "af-ZA", region: "Afrique" },
  { code: "st", name: "Sotho", flag: "🇱🇸", speech: "st", region: "Afrique" },
  { code: "so", name: "Somali", flag: "🇸🇴", speech: "so-SO", region: "Afrique" },
  { code: "rw", name: "Kinyarwanda", flag: "🇷🇼", speech: "rw-RW", region: "Afrique" },
  { code: "rn", name: "Kirundi", flag: "🇧🇮", speech: "rn", region: "Afrique" },
  { code: "ln", name: "Lingala", flag: "🇨🇩", speech: "ln", region: "Afrique" },
  { code: "sn", name: "Shona", flag: "🇿🇼", speech: "sn-ZW", region: "Afrique" },
  { code: "ny", name: "Chichewa", flag: "🇲🇼", speech: "ny", region: "Afrique" },
  { code: "wo", name: "Wolof", flag: "🇸🇳", speech: "wo", region: "Afrique" },
  { code: "ti", name: "Tigrigna", flag: "🇪🇷", speech: "ti", region: "Afrique" },
  { code: "om", name: "Oromo", flag: "🇪🇹", speech: "om", region: "Afrique" },
  { code: "mg", name: "Malgache", flag: "🇲🇬", speech: "fr-FR", region: "Afrique" },
  { code: "mos", name: "Mooré", flag: "🇧🇫", speech: "mos", region: "Afrique" },

  // --- Asie ---
  { code: "zh", name: "Chinois (simplifié)", flag: "🇨🇳", speech: "zh-CN", region: "Asie" },
  { code: "zh-TW", name: "Chinois (traditionnel)", flag: "🇹🇼", speech: "zh-TW", region: "Asie" },
  { code: "ja", name: "Japonais", flag: "🇯🇵", speech: "ja-JP", region: "Asie" },
  { code: "ko", name: "Coréen", flag: "🇰🇷", speech: "ko-KR", region: "Asie" },
  { code: "vi", name: "Vietnamien", flag: "🇻🇳", speech: "vi-VN", region: "Asie" },
  { code: "th", name: "Thaï", flag: "🇹🇭", speech: "th-TH", region: "Asie" },
  { code: "id", name: "Indonésien", flag: "🇮🇩", speech: "id-ID", region: "Asie" },
  { code: "ms", name: "Malais", flag: "🇲🇾", speech: "ms-MY", region: "Asie" },
  { code: "tl", name: "Filipino (Tagalog)", flag: "🇵🇭", speech: "fil-PH", region: "Asie" },
  { code: "hi", name: "Hindi", flag: "🇮🇳", speech: "hi-IN", region: "Asie" },
  { code: "bn", name: "Bengali", flag: "🇧🇩", speech: "bn-BD", region: "Asie" },
  { code: "ta", name: "Tamoul", flag: "🇮🇳", speech: "ta-IN", region: "Asie" },
  { code: "te", name: "Télougou", flag: "🇮🇳", speech: "te-IN", region: "Asie" },
  { code: "ml", name: "Malayalam", flag: "🇮🇳", speech: "ml-IN", region: "Asie" },
  { code: "kn", name: "Kannada", flag: "🇮🇳", speech: "kn-IN", region: "Asie" },
  { code: "mr", name: "Marathi", flag: "🇮🇳", speech: "mr-IN", region: "Asie" },
  { code: "gu", name: "Goujarati", flag: "🇮🇳", speech: "gu-IN", region: "Asie" },
  { code: "pa", name: "Pendjabi", flag: "🇮🇳", speech: "pa-IN", region: "Asie" },
  { code: "or", name: "Odia", flag: "🇮🇳", speech: "or-IN", region: "Asie" },
  { code: "as", name: "Assamais", flag: "🇮🇳", speech: "as-IN", region: "Asie" },
  { code: "ur", name: "Ourdou", flag: "🇵🇰", speech: "ur-PK", region: "Asie" },
  { code: "ne", name: "Népalais", flag: "🇳🇵", speech: "ne-NP", region: "Asie" },
  { code: "si", name: "Cingalais", flag: "🇱🇰", speech: "si-LK", region: "Asie" },
  { code: "my", name: "Birman", flag: "🇲🇲", speech: "my-MM", region: "Asie" },
  { code: "km", name: "Khmer", flag: "🇰🇭", speech: "km-KH", region: "Asie" },
  { code: "lo", name: "Lao", flag: "🇱🇦", speech: "lo-LA", region: "Asie" },
  { code: "mn", name: "Mongol", flag: "🇲🇳", speech: "mn-MN", region: "Asie" },
  { code: "ceb", name: "Cebuano", flag: "🇵🇭", speech: "ceb", region: "Asie" },
  { code: "jv", name: "Javanais", flag: "🇮🇩", speech: "jv", region: "Asie" },
  { code: "su", name: "Soundanais", flag: "🇮🇩", speech: "su", region: "Asie" },

  // --- Asie centrale ---
  { code: "kk", name: "Kazakh", flag: "🇰🇿", speech: "kk-KZ", region: "Asie centrale" },
  { code: "ky", name: "Kirghiz", flag: "🇰🇬", speech: "ky-KG", region: "Asie centrale" },
  { code: "uz", name: "Ouzbek", flag: "🇺🇿", speech: "uz-UZ", region: "Asie centrale" },
  { code: "tg", name: "Tadjik", flag: "🇹🇯", speech: "tg-TJ", region: "Asie centrale" },
  { code: "tk", name: "Turkmène", flag: "🇹🇲", speech: "tk-TM", region: "Asie centrale" },

  // --- Amériques ---
  { code: "es-MX", name: "Espagnol (Mexique)", flag: "🇲🇽", speech: "es-MX", region: "Amériques" },
  { code: "ht", name: "Créole haïtien", flag: "🇭🇹", speech: "fr-FR", region: "Amériques" },
  { code: "qu", name: "Quechua", flag: "🇵🇪", speech: "qu", region: "Amériques" },
  { code: "gn", name: "Guarani", flag: "🇵🇾", speech: "gn", region: "Amériques" },

  // --- Océanie ---
  { code: "mi", name: "Maori", flag: "🇳🇿", speech: "mi-NZ", region: "Océanie" },
  { code: "sm", name: "Samoan", flag: "🇼🇸", speech: "sm", region: "Océanie" },
  { code: "to", name: "Tongien", flag: "🇹🇴", speech: "to", region: "Océanie" },
  { code: "fj", name: "Fidjien", flag: "🇫🇯", speech: "fj", region: "Océanie" },
  { code: "haw", name: "Hawaïen", flag: "🇺🇸", speech: "haw", region: "Océanie" },
];
